/* AI assistant memory: isolated from task/billing data and stored only in localStorage. */
(function(){
const KEYS={profile:'tm_ai_user_profile_v1',weeks:'tm_ai_weekly_summary_v1',feedback:'tm_ai_feedback_log_v1'};
const MAX_WEEKS=16,MAX_FEEDBACK=400;
const parse=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch(e){return fallback}};
const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const iso=()=>new Date().toISOString();
const dayKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const monday=value=>{const d=new Date((value||dayKey(new Date()))+'T12:00:00'),n=d.getDay()||7;d.setDate(d.getDate()-n+1);return dayKey(d)};
const weekEnd=start=>{const d=new Date(start+'T12:00:00');d.setDate(d.getDate()+6);return dayKey(d)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lifeRhythmLines=appData=>Object.values(appData?.v2?.lifeRhythm?.days||{}).sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,5).map(x=>`${x.date}｜${[x.sleepStart&&x.wakeTime?`睡眠${x.sleepStart}-${x.wakeTime}${x.sleepQuality?`(${x.sleepQuality})`:''}`:'',x.energyLevel||'',x.rhythm?`节奏${x.rhythm}`:'',x.control?`掌控感${x.control}`:'',x.completionPercent?`完成${x.completionPercent}%`:'',x.rechargeTags?.length?`补能:${x.rechargeTags.slice(0,2).join('、')}`:'',x.drainTags?.length?`消耗:${x.drainTags.slice(0,2).join('、')}`:'',x.rhythmFactors?.length?`打断:${x.rhythmFactors.slice(0,2).join('、')}`:(x.interrupts?.length?`打断:${x.interrupts.slice(0,2).join('、')}`:''),x.hiddenCosts?.length?`隐形成本:${x.hiddenCosts.slice(0,2).map(i=>i.title).join('、')}`:''].filter(Boolean).join(' · ')}`);
const eatingLines=appData=>(appData?.v2?.eatingLogs||[]).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,5).map(x=>`${x.date}｜${[x.moment||'时间未写',x.level||'',x.trigger?`诱因:${x.trigger}`:'',x.mood?`心情:${x.mood}`:'',x.note?`备注:${String(x.note).slice(0,36)}`:''].filter(Boolean).join(' · ')}`);
const lateNightLines=appData=>(appData?.v2?.lateNightLogs||[]).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,5).map(x=>`${x.date}｜${[x.bedtime?`入睡:${x.bedtime}`:'时间未写',x.trigger?`原因:${x.trigger}`:'',x.mood?`心情:${x.mood}`:'',x.nextDay?`次日:${x.nextDay}`:'',x.note?`备注:${String(x.note).slice(0,36)}`:''].filter(Boolean).join(' · ')}`);

const userProfile={
  defaults(){return{version:1,preferences:{maxTaskTypesPerDay:3,choresPerDay:1,insertLowResistance:true,proactivePush:true,suggestionTime:'09:00',quietStart:'22:30',quietEnd:'07:30'},principles:'一天不超过三种任务类型；精力低时优先低阻力任务；家务少量穿插；AI建议只能使用普通通知，不能擅自设置重要闹钟。',learnedRules:[],lastAutoWeek:null,createdAt:iso(),updatedAt:iso()}},
  load(){return Object.assign(this.defaults(),parse(KEYS.profile,{}),{preferences:Object.assign(this.defaults().preferences,parse(KEYS.profile,{})?.preferences||{})})},
  save(value){value.updatedAt=iso();save(KEYS.profile,value);return value},
  syncPlanner(appData){const existing=parse(KEYS.profile,null);if(existing)return this.load();const p=this.load(),source=appData?.v2?.planner?.profile;if(source){p.preferences.maxTaskTypesPerDay=source.maxTaskTypes||p.preferences.maxTaskTypesPerDay;p.preferences.choresPerDay=source.choresPerDay??p.preferences.choresPerDay;p.preferences.insertLowResistance=source.insertLowResistance??p.preferences.insertLowResistance;if(source.principles)p.principles=source.principles}return this.save(p)},
  learn(log){const p=this.load(),recent=log.slice(-120),groups={};recent.forEach(x=>{const key=(x.suggestion?.type||'任务')+'|'+(x.suggestion?.title||'').replace(/[，。！？\s]/g,'').slice(0,24);if(!key.endsWith('|')){groups[key]=groups[key]||{title:x.suggestion.title,type:x.suggestion.type,accepted:0,skipped:0};groups[key][x.action==='accepted'?'accepted':'skipped']++}});p.learnedRules=Object.values(groups).filter(x=>Math.max(x.accepted,x.skipped)>=2).sort((a,b)=>Math.max(b.accepted,b.skipped)-Math.max(a.accepted,a.skipped)).slice(0,20).map(x=>({id:(x.type+'-'+x.title).slice(0,40),rule:x.accepted>x.skipped?`倾向采纳「${x.title}」类${x.type||'任务'}`:`尽量少推荐「${x.title}」类${x.type||'任务'}`,signal:x.accepted>x.skipped?'prefer':'avoid',score:Math.abs(x.accepted-x.skipped),updatedAt:iso()}));this.save(p)}
};

const feedbackLog={
  load(){return parse(KEYS.feedback,[])},
  record(action,suggestion,context={}){const list=this.load();list.push({id:'fb-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),action,suggestion:{title:suggestion?.title||suggestion?.text||'',type:suggestion?.type||'任务'},context:{date:context.date||dayKey(new Date()),energy:context.energy||'',freeTime:context.freeTime||'',source:context.source||'ai-chat'},createdAt:iso()});const trimmed=list.slice(-MAX_FEEDBACK);save(KEYS.feedback,trimmed);userProfile.learn(trimmed);return trimmed},
  stats(start,end){const list=this.load().filter(x=>(!start||x.context.date>=start)&&(!end||x.context.date<=end));return{accepted:list.filter(x=>x.action==='accepted').length,skipped:list.filter(x=>x.action==='skipped').length,total:list.length}}
};

const weeklySummary={
  load(){return parse(KEYS.weeks,[])},
  generate(appData,start=monday()){const end=weekEnd(start),plans=appData?.v2?.dayPlans||{},items=[];Object.entries(plans).forEach(([date,plan])=>{if(date>=start&&date<=end)(plan.items||[]).forEach(item=>items.push({...item,date}))});const completed=items.filter(x=>x.status==='done'),unfinished=items.filter(x=>x.status!=='done'),types={};completed.forEach(x=>types[x.type||'任务']=(types[x.type||'任务']||0)+1);const frequent=Object.entries(completed.reduce((m,x)=>(m[x.title]=(m[x.title]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]).slice(0,5),feedback=feedbackLog.stats(start,end);const text=[`${start} 至 ${end}`,`计划 ${items.length} 项，完成 ${completed.length} 项，未完成 ${unfinished.length} 项。`,Object.keys(types).length?`完成类型：${Object.entries(types).map(([k,v])=>`${k}${v}项`).join('、')}。`:'本周尚无完成记录。',frequent.length?`重复推进：${frequent.map(([k,v])=>`${k}×${v}`).join('、')}。`:'',feedback.total?`AI建议：采纳 ${feedback.accepted}，跳过 ${feedback.skipped}。`:''].filter(Boolean).join('\n');const entry={id:'week-'+start,startDate:start,endDate:end,generatedAt:iso(),stats:{planned:items.length,completed:completed.length,unfinished:unfinished.length,types,feedback},topCompleted:frequent.map(([title,count])=>({title,count})),unfinishedTitles:unfinished.map(x=>x.title).slice(0,12),conversationDigests:[],text};const weeks=this.load().filter(x=>x.startDate!==start);weeks.push(entry);weeks.sort((a,b)=>a.startDate.localeCompare(b.startDate));save(KEYS.weeks,weeks.slice(-MAX_WEEKS));return entry},
  addConversationDigest(text){if(!text)return;const start=monday(),weeks=this.load();let week=weeks.find(x=>x.startDate===start);if(!week){week={id:'week-'+start,startDate:start,endDate:weekEnd(start),generatedAt:iso(),stats:{},topCompleted:[],unfinishedTitles:[],conversationDigests:[],text:''};weeks.push(week)}week.conversationDigests=(week.conversationDigests||[]).concat(String(text).slice(0,1200)).slice(-4);week.generatedAt=iso();save(KEYS.weeks,weeks.slice(-MAX_WEEKS))},
  autoRoll(appData){const p=userProfile.load(),current=monday();if(p.lastAutoWeek&&p.lastAutoWeek!==current){const previous=new Date(current+'T12:00:00');previous.setDate(previous.getDate()-7);this.generate(appData,dayKey(previous))}if(p.lastAutoWeek!==current){p.lastAutoWeek=current;userProfile.save(p)}},
  current(){const start=monday();return this.load().find(x=>x.startDate===start)||null}
};

function buildPrompt(appData){userProfile.syncPlanner(appData);const profile=userProfile.load(),weeks=weeklySummary.load().slice(-2),feedback=feedbackLog.stats();return[
  '【用户长期规划底色｜跨对话保留】',profile.principles,
  `约束：每天最多${profile.preferences.maxTaskTypesPerDay}种任务；家务最多${profile.preferences.choresPerDay}项；${profile.preferences.insertLowResistance?'空余时穿插低阻力任务；':''}安静时段${profile.preferences.quietStart}-${profile.preferences.quietEnd}。`,
  lifeRhythmLines(appData).length?`【最近生活能量与节奏】\n${lifeRhythmLines(appData).join('\n')}\n规则：如果用户低电量、熬夜、被打断很多，就减少深度任务，多给短任务、缓冲和恢复建议。`:'',
  eatingLines(appData).length?`【最近饮食波动】\n${eatingLines(appData).join('\n')}\n规则：如果连续出现暴饮暴食、停不下来、夜晚补偿性进食，要把它视为压力/低电量信号，不要继续把今天排满。`:'',
  lateNightLines(appData).length?`【最近熬夜节点】\n${lateNightLines(appData).join('\n')}\n规则：如果连续熬夜或凌晨三点后睡，第二天默认降负，只给轻量、低阻力任务。`:'',
  profile.learnedRules.length?'【从采纳/跳过中学到】\n'+profile.learnedRules.map(x=>'- '+x.rule).join('\n'):'',
  weeks.length?'【最近周摘要】\n'+weeks.map(w=>w.text+(w.conversationDigests?.length?'\n对话摘要：'+w.conversationDigests.slice(-1)[0]:'')).join('\n---\n'):'',
  `【反馈总览】采纳${feedback.accepted}次，跳过${feedback.skipped}次。`,
  '规则：先尊重长期底色，再结合本周任务和当天精力给建议；一次最多建议3项；AI建议不得自动升级为重要闹钟。'
].filter(Boolean).join('\n\n').slice(0,10000)}

function nextSuggestion(appData){const p=userProfile.load();if(!p.preferences.proactivePush)return null;const today=dayKey(new Date()),already=appData?.v2?.dayPlans?.[today]?.items||[],rules=p.learnedRules.filter(x=>x.signal==='prefer'),tasks=appData?.tasks||[];const state=appData?.v2?.lifeRhythm?.days?.[today]||null;let candidate=rules.map(r=>tasks.find(t=>r.rule.includes(t.title))).find(Boolean);if(!candidate){const history={};Object.values(appData?.v2?.dayPlans||{}).forEach(plan=>(plan.items||[]).filter(x=>x.status==='done').forEach(x=>history[x.title]=(history[x.title]||0)+1));const title=Object.entries(history).sort((a,b)=>b[1]-a[1]).find(([name])=>!already.some(x=>x.title===name))?.[0];candidate=tasks.find(t=>t.title===title)||title&&{title,type:'每日'}}if(!candidate||already.some(x=>x.title===candidate.title))return null;const lowEnergy=state&&(state.energyLevel==='低电量'||['很乱','被打乱','完全被打乱'].includes(state.rhythm)||state.control==='低'||(state.rhythmFactors||state.interrupts||[]).length>=3||state.sleepQuality==='差'||state.stayedUpLate==='是'||(Number(state.completionPercent||0)>0&&Number(state.completionPercent)<40));const softTitle=state?.rechargeTop||((state?.rechargeTags||[])[0]);return{title:candidate.title,type:candidate.type||'每日',time:p.preferences.suggestionTime,text:lowEnergy?`看起来你今天状态偏低，先别把自己压太满。要不要只保留一件轻量任务「${candidate.title}」${softTitle?`，做完再去${softTitle}一下`:'？'}`:`最近常在推进「${candidate.title}」，今天要继续吗？`}}

function exportAll(){return{profile:userProfile.load(),weeklySummary:weeklySummary.load(),feedbackLog:feedbackLog.load()}}
function importAll(bundle){
  if(!bundle||typeof bundle!=='object')return false;
  if(bundle.profile)save(KEYS.profile,Object.assign(userProfile.defaults(),bundle.profile,{preferences:Object.assign(userProfile.defaults().preferences,bundle.profile.preferences||{})}));
  if(Array.isArray(bundle.weeklySummary))save(KEYS.weeks,bundle.weeklySummary.slice(-MAX_WEEKS));
  if(Array.isArray(bundle.feedbackLog))save(KEYS.feedback,bundle.feedbackLog.slice(-MAX_FEEDBACK));
  return true
}

function injectUI(appData){
  const oldSummary=document.getElementById('chatSummaryBtn');if(oldSummary)oldSummary.style.display='none';
  const toolbar=document.querySelector('.chat-toolbar');if(toolbar&&!document.getElementById('aiWeekSummaryBtn')){const week=document.createElement('button');week.id='aiWeekSummaryBtn';week.textContent='生成本周摘要';week.addEventListener('click',()=>{const result=weeklySummary.generate(appData);window.v2Toast?.('本周摘要已生成');alert(result.text)});const memory=document.createElement('button');memory.id='aiMemoryBtn';memory.textContent='查看我的记忆';memory.addEventListener('click',()=>showMemory(appData));toolbar.prepend(memory);toolbar.prepend(week)}
  if(!document.getElementById('aiMemoryPopup')){const popup=document.createElement('div');popup.id='aiMemoryPopup';popup.className='summary-popup ai-memory-popup';popup.innerHTML='<div class="box"><h3>🧠 AI 对我的记忆</h3><div id="aiMemoryBody"></div><div class="v2-row end"><button class="close-btn" id="aiMemoryClose">关闭</button></div></div>';document.body.appendChild(popup);document.getElementById('aiMemoryClose').addEventListener('click',()=>popup.classList.remove('show'));popup.addEventListener('click',e=>{if(e.target===popup)popup.classList.remove('show')})}
  const newChat=document.getElementById('chatNewBtn');if(newChat&&!newChat.dataset.memoryHook){newChat.dataset.memoryHook='1';newChat.addEventListener('click',()=>{if(typeof chatHistory!=='undefined'&&chatHistory.length){const digest=chatHistory.slice(-10).map(x=>`${x.role==='user'?'我':'AI'}：${x.content}`).join('\n').slice(0,1200);weeklySummary.addConversationDigest(digest)}},{capture:true})}
  installFeedbackButtons(appData)
}
function showMemory(appData){const p=userProfile.load(),weeks=weeklySummary.load().slice(-4).reverse(),log=feedbackLog.load().slice(-12).reverse(),stats=feedbackLog.stats(),body=document.getElementById('aiMemoryBody');body.innerHTML=`<div class="ai-memory-block"><b>固化习惯偏好</b><label>长期规划原则<textarea id="aiPrinciples" rows="4">${esc(p.principles)}</textarea></label><div class="v2-grid"><label>每天最多任务类型<input id="aiMaxTypes" type="number" min="1" max="6" value="${p.preferences.maxTaskTypesPerDay}"></label><label>每天最多家务<input id="aiMaxChores" type="number" min="0" max="5" value="${p.preferences.choresPerDay}"></label></div><label>主动建议时间<input id="aiSuggestTime" type="time" value="${p.preferences.suggestionTime}"></label><label><input id="aiProactive" type="checkbox" ${p.preferences.proactivePush?'checked':''}> 允许AI根据习惯发普通任务建议</label><button class="v2-primary" id="aiProfileSave">保存固化习惯</button></div><div class="ai-memory-block"><b>AI学到的倾向</b>${p.learnedRules.length?p.learnedRules.map(x=>`<p>• ${esc(x.rule)}</p>`).join(''):'<p class="hint">采纳或跳过几次建议后，这里会逐渐形成规则。</p>'}</div><div class="ai-memory-block"><b>每周摘要</b>${weeks.length?weeks.map(w=>`<details><summary>${w.startDate} ～ ${w.endDate}</summary><pre>${esc(w.text)}</pre></details>`).join(''):'<p class="hint">暂无周摘要。</p>'}</div><div class="ai-memory-block"><b>反馈记录</b><p class="hint">累计采纳 ${stats.accepted}，跳过 ${stats.skipped}</p>${log.map(x=>`<p>${x.action==='accepted'?'✅':'⏭'} ${esc(x.suggestion.title)}</p>`).join('')}</div>`;document.getElementById('aiProfileSave').addEventListener('click',()=>{p.principles=document.getElementById('aiPrinciples').value.trim();p.preferences.maxTaskTypesPerDay=Number(document.getElementById('aiMaxTypes').value)||3;p.preferences.choresPerDay=Number(document.getElementById('aiMaxChores').value)||0;p.preferences.suggestionTime=document.getElementById('aiSuggestTime').value||'09:00';p.preferences.proactivePush=document.getElementById('aiProactive').checked;userProfile.save(p);alert('长期记忆已保存')});document.getElementById('aiMemoryPopup').classList.add('show')}

function installFeedbackButtons(appData){const enhance=()=>document.querySelectorAll('.chat-suggest-item').forEach((row,index)=>{if(row.dataset.memoryReady)return;row.dataset.memoryReady='1';const add=row.querySelector('[data-chat-add]');if(!add)return;add.textContent='✅ 采纳';const skip=document.createElement('button');skip.className='chat-add-btn ai-skip-btn';skip.textContent='跳过';skip.addEventListener('click',()=>{const suggestion=JSON.parse(add.dataset.chatAdd||'{}');feedbackLog.record('skipped',suggestion,{energy:appData.todayStatus?.energy,freeTime:appData.todayStatus?.freeTime,source:'ai-chat'});row.remove()});add.addEventListener('click',()=>{const suggestion=JSON.parse(add.dataset.chatAdd||'{}');feedbackLog.record('accepted',suggestion,{energy:appData.todayStatus?.energy,freeTime:appData.todayStatus?.freeTime,source:'ai-chat'})},{once:true});row.appendChild(skip)});new MutationObserver(enhance).observe(document.getElementById('chatMessages'),{childList:true,subtree:true});enhance()}

function init(appData){userProfile.syncPlanner(appData);weeklySummary.autoRoll(appData);injectUI(appData);return{profile:userProfile.load(),currentWeek:weeklySummary.current()}}
window.AIMemorySystem={init,userProfile,weeklySummary,feedbackLog,buildPrompt,nextSuggestion,showMemory,exportAll,importAll};
})();
